// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVOXzOFvfcQWF0l_KF2JzgkxG3eljBwcg',
    appId: '1:892628944409:web:1fea0c79e598438bca8c88',
    messagingSenderId: '892628944409',
    projectId: 'nexus-3c84b',
    authDomain: 'nexus-3c84b.firebaseapp.com',
    storageBucket: 'nexus-3c84b.appspot.com',
    measurementId: 'G-26E548H012',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD9iKSZeixkvvTy3VSS89yfi3NdtCc60U',
    appId: '1:892628944409:android:7cbe522c7d2a8921ca8c88',
    messagingSenderId: '892628944409',
    projectId: 'nexus-3c84b',
    storageBucket: 'nexus-3c84b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoBcFyQm76y0Xr2DdQs-xTyKJAqI_4kBU',
    appId: '1:892628944409:ios:512f6a554cbf44cbca8c88',
    messagingSenderId: '892628944409',
    projectId: 'nexus-3c84b',
    storageBucket: 'nexus-3c84b.appspot.com',
    iosBundleId: 'com.example.nexusApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoBcFyQm76y0Xr2DdQs-xTyKJAqI_4kBU',
    appId: '1:892628944409:ios:512f6a554cbf44cbca8c88',
    messagingSenderId: '892628944409',
    projectId: 'nexus-3c84b',
    storageBucket: 'nexus-3c84b.appspot.com',
    iosBundleId: 'com.example.nexusApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVOXzOFvfcQWF0l_KF2JzgkxG3eljBwcg',
    appId: '1:892628944409:web:6b14bb7a53fa7bd7ca8c88',
    messagingSenderId: '892628944409',
    projectId: 'nexus-3c84b',
    authDomain: 'nexus-3c84b.firebaseapp.com',
    storageBucket: 'nexus-3c84b.appspot.com',
    measurementId: 'G-SGJ7N3Q1L4',
  );

}